spring:
  application:
    name: omadata-oauth2-sample
  ssl:
    bundle:
      pem:
        koski-ssl-bundle:
          keystore:
            certificate: "${jod.koski.client-cert:../koski-luovutuspalvelu/proxy/test/testca/certs/client.crt}"
            private-key: "${jod.koski.client-key:../koski-luovutuspalvelu/proxy/test/testca/private/client.key}"
          truststore:
            certificate: "${jod.koski.server-cert:../koski-luovutuspalvelu/proxy/test/testca/certs/root-ca.crt}"
  security:
    oauth2:
      client:
        registration:
          koski:
            provider: koski-tls
            client-id: omadataoauth2sample
            client-authentication-method: none
            authorization-grant-type: authorization_code
            #scope: HENKILOTIEDOT_HETU,OPISKELUOIKEUDET_KAIKKI_TIEDOT
            scope: HENKILOTIEDOT_KAIKKI_TIEDOT,OPISKELUOIKEUDET_KAIKKI_TIEDOT
            client-name: koski
            redirect-uri: "{baseUrl}/oauth2/code/{registrationId}"
        provider:
          koski-tls:
            token-uri: https://localhost:7022/koski/api/omadata-oauth2/authorization-server
            authorization-uri: http://localhost:7021/koski/omadata-oauth2/authorize
server:
  port: 7051
koski:
  resource-server:
    url: https://localhost:7022/koski/api/omadata-oauth2/resource-server
logging:
  level:
    org.springframework.security: TRACE
